<?php
    /* @var $this Loewenstark_Gtag_Block_Ga */
    $_accountId = $this->getAccountId();
    $_ga4accountId = $this->getGa4AccountId();
?>
<?php if($_accountId): ?>
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $_accountId ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  <?php if($this->getAccountIdIsUa()): ?>
    gtag('config', '<?php echo $_accountId ?>', <?php echo $this->getGtagOptions() ?>);
  <?php else: ?>
    gtag('config', '<?php echo $_accountId ?>');
  <?php endif; ?>
  <?php if($_ga4accountId): ?>
      gtag('config', '<?php echo $_ga4accountId ?>');
  <?php endif; ?>
  <?php if($this->getAwAccountOnce()): ?>
    gtag('config', '<?php echo $this->getAwAccount() ?>');
  <?php endif; ?>
<?php echo $this->getEcommerceTracking(); ?>
<?php echo $this->getConversionTracking(); ?>
</script>
<?php endif; ?>
