<?php
    /* @var $this Loewenstark_Gtag_Block_Ga */
    $_helper = $this->helper('gtag');
    /* @var $_helper Loewenstark_Gtag_Helper_Data */
    $_accountId = $_helper->getAccountId();
?>
<?php if($_accountId): ?>
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $_accountId ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '<?php echo $_accountId ?>', <?php echo $this->getGtagOptions() ?>);
    
  <?php if($this->getAwAccountOnce()): ?>
	  gtag('config', '<?php echo $this->getAwAccount() ?>');
  <?php endif; ?>

<?php echo $this->getOrdersTrackingCode(); ?>
</script>
<?php endif; ?>
